"""Domain entities for the users module."""

from dataclasses import dataclass
from datetime import UTC, datetime

from app.modules.users.domain.enums import UserRole
from app.modules.users.domain.exceptions import EmptyPasswordHashError
from app.modules.users.domain.value_objects import Email


@dataclass(slots=True)
class User:
    """Application user with authentication and activation state."""

    id: str | None
    email: Email
    password_hash: str
    role: UserRole
    is_active: bool
    created_at: datetime
    updated_at: datetime

    @classmethod
    def create(cls, email: str, password_hash: str) -> "User":
        """Create an active user with the default role.

        Args:
            email: User email address.
            password_hash: Password hash generated by an application port.

        Returns:
            A new active user without a persistence identifier.

        Raises:
            InvalidEmailError: If the email address is invalid.
            EmptyPasswordHashError: If the password hash is blank.
        """
        if not password_hash.strip():
            raise EmptyPasswordHashError()

        now = datetime.now(UTC)

        return cls(
            id=None,
            email=Email.create(email),
            password_hash=password_hash,
            role=UserRole.USER,
            is_active=True,
            created_at=now,
            updated_at=now,
        )

    def deactivate(self) -> None:
        """Prevent the user from authenticating."""
        self.is_active = False
        self.updated_at = datetime.now(UTC)

    def activate(self) -> None:
        """Allow the user to authenticate."""
        self.is_active = True
        self.updated_at = datetime.now(UTC)

    def change_email(self, email: str) -> None:
        """Replace the user's email with a validated value."""
        self.email = Email.create(email)
        self.updated_at = datetime.now(UTC)

    def change_password_hash(self, password_hash: str) -> None:
        """Replace the password hash without receiving a raw password."""
        if not password_hash.strip():
            raise EmptyPasswordHashError()
        self.password_hash = password_hash
        self.updated_at = datetime.now(UTC)
